from Lib.library import Base
from time import sleep

class address(Base):
    newsletter_textbox=('xpath','//input[@name="NewsletterEmail"]')
    subscribe_btn=('xpath','//input[@value="Subscribe"]')
    Address_option=('xpath',"//a[text()='Addresses']")
    Addnew_btn=('xpath','//input[@value="Add new"]')
    f_name_textbox=('xpath','//input[@name="Address.FirstName"]')
    l_name_textbox=('xpath','//input[@name="Address.LastName"]')
    email_textbox=('xpath','//input[@name="Address.Email"]')
    country_drpdown=('xpath','//select[@name="Address.CountryId"]')
    state_drpdown=('xpath','//select[@name="Address.StateProvinceId"]')
    city_textbox=('xpath','//input[@name="Address.City"]')
    Address1_textbox=('xpath','//input[@name="Address.Address1"]')
    Address2_textbox=('xpath','//input[@name="Address.Address2"]')
    postalcode_textbox=('xpath','//input[@name="Address.ZipPostalCode"]')
    phonenumber_textbox=('xpath','//input[@name="Address.PhoneNumber"]')
    Faxnumber_textbox=('xpath','//input[@name="Address.FaxNumber"]')
    save_btn=('xpath','//input[@value="Save"]')
    Edit_btn=('xpath',"//li[contains(text(),'Rony Mahesh')]/../..//input[@value='Edit']")
    Edit_Add_city=('xpath','//input[@name="Address.City"]')
    Delete_btn=('xpath',"//li[contains(text(),'Rony Mahesh')]/../..//input[@value='Delete']")

    def add(self,newletter_emailid,fname,lname,email,city,Address1,Address2,postalcode,phonenumer,Faxnumber):
        self.send_data(self.newsletter_textbox,newletter_emailid)
        sleep(2)
        self.click_element(self.subscribe_btn)
        sleep(2)
        self.click_element(self.Address_option)
        sleep(2)
        self.click_element(self.Addnew_btn)
        sleep(2)
        self.send_data(self.f_name_textbox,fname)
        sleep(2)
        self.send_data(self.l_name_textbox,lname)
        sleep(2)
        self.send_data(self.email_textbox,email)
        sleep(2)
        self.country_drp(self.country_drpdown)
        sleep(2)
        self.state_drp(self.state_drpdown)
        sleep(2)
        self.send_data(self.city_textbox,city)
        sleep(2)
        self.send_data(self.Address1_textbox,Address1)
        sleep(2)
        self.send_data(self.Address2_textbox,Address2)
        sleep(2)
        self.send_data(self.postalcode_textbox,postalcode)
        sleep(2)
        self.send_data(self.phonenumber_textbox,phonenumer)
        sleep(2)
        self.send_data(self.Faxnumber_textbox,Faxnumber)
        sleep(2)
        self.click_element(self.save_btn)
        sleep(2)
        self.click_element(self.Edit_btn)
        sleep(2)
        self.clear_data(self.Edit_Add_city)
        sleep(2)
        self.send_data(self.Edit_Add_city,'Mysuru')
        sleep(2)
        self.click_element(self.save_btn)
        sleep(2)
        self.click_element(self.Delete_btn)
        sleep(2)
        self.alert_pop()



