from Lib.library import Base
from time import sleep

class Buy(Base):
    Books_option=('xpath','//ul[@class="top-menu"]//a[@href="/books"]')
    fiction_Book_addtocart_locator=('xpath','//h2[@class="product-title"]//a[text()="Fiction"]/../../..//input[@value="Add to cart"]')
    shoppincart_btn=('xpath',"//a[text()='shopping cart']")
    TC_checkbox=('xpath','//input[@name="termsofservice"]')
    checkout_btn=('xpath','//button[@name="checkout"]')
    Billing_continue_btn=('xpath','//div[@id="billing-buttons-container"]//input[@value="Continue"]')
    shipping_continue_btn=('xpath','//div[@id="shipping-buttons-container"]//input[@value="Continue"]')
    shipping_method_continue_btn=('xpath','//div[@id="shipping-method-buttons-container"]//input[@value="Continue"]')
    payment_method_continue_btn=('xpath','//div[@id="payment-method-buttons-container"]//input[@value="Continue"]')
    payment_information_continue_btn=('xpath','//div[@id="payment-info-buttons-container"]//input[@value="Continue"]')
    confirm_order_btn=('xpath','//div[@id="confirm-order-buttons-container"]//input[@value="Confirm"]')

    def order(self):
        self.click_element(self.Books_option)
        sleep(2)
        self.click_element(self.fiction_Book_addtocart_locator)
        sleep(2)
        self.click_element(self.shoppincart_btn)
        sleep(2)
        self.click_element(self.TC_checkbox)
        sleep(2)
        self.click_element(self.checkout_btn)
        sleep(2)
        self.click_element(self.Billing_continue_btn)
        sleep(2)
        self.click_element(self.shipping_continue_btn)
        sleep(2)
        self.click_element(self.shipping_method_continue_btn)
        sleep(2)
        self.click_element(self.payment_method_continue_btn)
        sleep(2)
        self.click_element(self.payment_information_continue_btn)
        sleep(2)
        self.click_element(self.confirm_order_btn)
        sleep(2)